services:
  web:
    container_name: video-collection
    restart: unless-stopped
    build: .
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: username
      DB_PASSWORD: password
      DB_DATABASE: movies
      EMBY_API_KEY: your-emby-apikey
      EMBY_SERVER_URL: http://your-emby-server-address
      JACKETT_URL: http://your-jackett-server-address
      THUNDER_URL: http://your-thunder-server-address
    volumes:
      - ./images:/images

  db:
    image: mariadb:10.5
    container_name: video-collection-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: movies
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - ./:/var/lib/mysql:rw
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uusername -ppassword"]
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin
    container_name: video-collection-phpmyadmin
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
